language: node_js
node_js:
  - '10'

cache:
  directories:
    - node_modules

env:
  global:
    - _CLOC_VERSION=1.80
    - PACKAGE_VERSION=1.0.0-$TRAVIS_BUILD_NUMBER

install:
  - if [ ! -d .tmp ]; then mkdir .tmp; fi
  # CLOC
  - if [ ! -f .tmp/cloc.pl ]; then wget -nv -O .tmp/cloc.pl https://github.com/AlDanial/cloc/releases/download/v$_CLOC_VERSION/cloc-$_CLOC_VERSION.pl; fi
  - npm install --no-package-lock --no-shrinkwrap

before_script:
  - npm --no-git-tag-version version $PACKAGE_VERSION
script:
  - npm run-script release --loglevel notice

deploy:
  - provider: npm
    email:
      secure: fBvxuZSuPASJQnCwz15037tWxqk2HdnKFeKccBDfeeiNqfYak95rymH9e64IWxHc2SBqLxo2VhwBZxLZYOy7pEw2DtzXatB2b1g9+kDTmjJRBHcOvtUdWh3rQ8U2xGfd4IhRV7jTQJAPoJhZzP/0gFsoF6T6VaQjz6EjA2KqbS6sD27Wh4x30i2nuUmaIgCAHwbxyIHe4Gn5GKiepersG2IDp0NGwNaEsCfQyMqOXGbVMAqWUkmBNePBjPL1Va4rgC3ITYGJKw8aRcWmYby5oxgPzHGL6Zb9wrEZtREYokwhneze2aXc4qTBeFtDz5tURWz1ejqXniAqKJdSiwc1wN6xk21gYS4x0FdHRx/yS04zuHh+tOEzn0LXisYjQyAEufcRbuNoekegVmo2H+odUDDdS3nprBLv3rZLv3Zm0wiemIRHA+xVipA9bOwc8rcyVlQGKgSdK3KI7/tOW/2pYk62IhB8P1u9L+Y2nDDjeQmfYQKN7tjJX8nL9cyRvuEihmieJyvCx5m+q0g3FB7JfAXmQF7IIfQ8Z0N/IP3fTN1beEmTa+gFyYYOn+JNkXFLTk+n3nN/gASzFANS6SCbi1kKUT02QVF8OQjFKE6kj3q/YZDLJOHXCq+CpHghS4wz1nUZ8CEQKm472RkIWx343Y9ZS9o+yb2Z95lBBOdmhlg=
    api_key:
      secure: izdl+DHsM6Y/tP0rNRvgZzXOt656rM8ufL31NZfmLUgXE3CfPeNc0EK3pv5maKRwa6q70ecxgJ54rZKjO+h0JVAmtjw/TVZdLyi/Z05ndbOTkK+Y8G+QRL19KlcI0a8tpcjpRfvzXJm7OfUsLUZxHolshGzHkcpyVi86nIGhnlSzaq1wMWaOvSlEMBqa0qp0rI5uweNNk/U/0h4LVtak7wqn94wnOQPN3QcYXKrMJzOH8+2TeAI8Dtv7fq1IVhDE0PHheL6kYtpAkwYOmIEmV/zrGiELdj++1Qp1HlXLbbgb5Iv4c+atrSbVoPTxQKkdmLctJViYabEkLZ4/gHo3dZBg7vOp7Hoifeu0FBf3rY015uLfhw4aXAZfU3T5k2PUQ+r0qzC1dOuQmi3iVDyRLFRT62SeJ1upja95lVv9vV2qwWd5oPFbMZFXFsADWAilqL328xZ6S28upmttMzs/ePQGlMrqeKq3iVf+huMxAfM1GMxRx8IM8sV8EAIePixg5XwBQ3mWqUfw46A8Wl2aU+Bh2+YpJj7tGWlYJtZ/DN8PGQinswpsQ+E7mnEBOpjZphPrCsOXKXu3+jczedZ3+OKWsHsTtRDWx4dO1alYdpeMmNnyG+mospCWKKYDoY7vuQAX9eIL/3UPyYKyYJe5KNFt/+O4Dz2mhbvYqHE8Toc=
    skip_cleanup: true
    on:
      tags: true
  - provider: releases
    api_key:
      secure: XQFlToAXpwJpSg70gQME4LrP32kduDFpsoXazrf66o0WzZSql2DtsqQwYqmow46v0E/LYymEsxFNL8caHm+wt/CSNDkqBt+9Z235Hrg679/8GahI/Sg210vrThW3yQ/c9GIaZA9cGxXmNpZziQTK3/DP+nz4xFPeKIIVvUfrcQR0prfEd/GFLHc63aqG1pi4Futy0YhsggF8g8YopwKawSFHH5hw4b1RTZuwLBsBm+YOQyubD8hdQDrPQe4ai385bTIpWoNgtkaJKBLtSkYBgJmPJQ2vqmrTIzD+jXsplcGSmicoISaI1t3hOXjbd93NHhR6/lmYDT2W1bZ1yYRnP6kqo/plAi326lDxIpPg4L+mgtBnLI1ejYODRSb9jfM5C4NHaZf1sHP8NwDABFrgo1RJoEPrbzcTye81HQ64EB9Kp8nSxscYATsD0g+S/fFmqursh+o6MhwvAPM3YMvKlvrd4+RN3vbl8B8FPw9zcN2uhdaCXwdhkBvPqBVlQVmYi7PLyctUjWtWzda6R3fC+iBiM0NmvkSvbngufprwgv6Jhp9Rdybfo8Q6+J+1ROxp5eVAoJhtP90zNdbzo/JThQuJRxOaKio7b3s10l+WdCvxbHxcihu6TDHhwJyBt0zx7Dh1YPBCqaRfG8T8BEwX+gnPwioCryKNQ3GMUgBOX8U=
    file_glob: true
    file: tmp/out/bin/*
    skip_cleanup: true
    on:
      tags: true
